### ISSUE TITLE
Report by Lejon

### ISSUE THREAD

**Issue by Lejon123** [Ghostriderdev/SuperLuckyBlock#1]
From console can't give luckyblocks, console log:      
17.04 20:47:50 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'slb' in plugin SuperLuckyBlock v1.1.4
17.04 20:47:50 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at com.mythicacraft.voteroulette.awards.AwardManager$5.run(AwardManager.java:1097) ~[?:?]
17.04 20:47:50 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]
17.04 20:47:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
17.04 20:47:50 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
17.04 20:47:50 [Server] INFO at me.ghostrider.superluckyblock.commands.SLBCommandExecutor.onCommand(SLBCommandExecutor.java:32) ~[?:?]
17.04 20:47:50 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.jar:git-Spigot-54ec0b8-e04a179]

**Comment by Ghostriderdev** [comment]
Fixed in the latest update!
